/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IntGestionCarta.java
 *
 * Created on 28-mar-2010, 17:14:59
 */

package Vista.InterfazCocinero;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;

/**
 *
 * @author Daniel
 */
public class IntGestionIngrediente extends javax.swing.JPanel {

    /** Creates new form IntGestionCarta */
    public IntGestionIngrediente() {
        initComponents();
        this.setDoubleBuffered(true);
    }

    @Override
    public void paint(Graphics g) {
        super.paintComponents(g);
        Graphics2D g2 = (Graphics2D) g.create();
        Rectangle clip = g2.getClipBounds();
        g2.setPaint(new GradientPaint(0.0f, 0.0f, new Color(170, 192, 249) ,getWidth() ,getHeight(), new Color(255, 255, 255) ));
        g2.fillRect(clip.x, clip.y, clip.width, clip.height);
        super.paint(g);
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        cabecera = new javax.swing.JPanel();
        contenedorDer = new javax.swing.JPanel();
        contenedorIzq = new javax.swing.JPanel();
        bVolver = new javax.swing.JButton();
        contenedorCentral = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        cuerpo = new javax.swing.JPanel();
        bAnadirIngrediente = new javax.swing.JButton();
        bEleminarIngrediente = new javax.swing.JButton();
        bModificarIngrediente = new javax.swing.JButton();
        bNotificarIncidente = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        cabecera.setMinimumSize(new java.awt.Dimension(50, 50));
        cabecera.setOpaque(false);
        cabecera.setLayout(new java.awt.BorderLayout());

        contenedorDer.setOpaque(false);
        contenedorDer.setPreferredSize(new java.awt.Dimension(200, 100));
        contenedorDer.setLayout(new java.awt.GridBagLayout());
        cabecera.add(contenedorDer, java.awt.BorderLayout.EAST);

        contenedorIzq.setOpaque(false);
        contenedorIzq.setPreferredSize(new java.awt.Dimension(200, 100));
        contenedorIzq.setLayout(new java.awt.GridBagLayout());

        bVolver.setFont(new java.awt.Font("Arial", 1, 14));
        bVolver.setForeground(new java.awt.Color(80, 98, 143));
        bVolver.setText("Volver");
        bVolver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bVolver.setPreferredSize(new java.awt.Dimension(100, 50));
        contenedorIzq.add(bVolver, new java.awt.GridBagConstraints());

        cabecera.add(contenedorIzq, java.awt.BorderLayout.WEST);

        contenedorCentral.setOpaque(false);
        contenedorCentral.setLayout(new java.awt.GridBagLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/InterfazCocinero/LogoSagres.png"))); // NOI18N
        logo.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/InterfazCocinero/LogoSagres.png"))); // NOI18N
        contenedorCentral.add(logo, new java.awt.GridBagConstraints());

        cabecera.add(contenedorCentral, java.awt.BorderLayout.CENTER);

        add(cabecera, java.awt.BorderLayout.PAGE_START);

        cuerpo.setMinimumSize(new java.awt.Dimension(800, 600));
        cuerpo.setOpaque(false);
        cuerpo.setLayout(new java.awt.GridBagLayout());

        bAnadirIngrediente.setFont(new java.awt.Font("Arial", 1, 14));
        bAnadirIngrediente.setForeground(new java.awt.Color(80, 98, 143));
        bAnadirIngrediente.setText("Añadir Ingrediente");
        bAnadirIngrediente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bAnadirIngrediente.setMaximumSize(new java.awt.Dimension(300, 200));
        bAnadirIngrediente.setMinimumSize(new java.awt.Dimension(300, 200));
        bAnadirIngrediente.setPreferredSize(new java.awt.Dimension(300, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        cuerpo.add(bAnadirIngrediente, gridBagConstraints);

        bEleminarIngrediente.setFont(new java.awt.Font("Arial", 1, 14));
        bEleminarIngrediente.setForeground(new java.awt.Color(80, 98, 143));
        bEleminarIngrediente.setText("Eliminar Ingrediente");
        bEleminarIngrediente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bEleminarIngrediente.setMaximumSize(new java.awt.Dimension(300, 200));
        bEleminarIngrediente.setMinimumSize(new java.awt.Dimension(300, 200));
        bEleminarIngrediente.setPreferredSize(new java.awt.Dimension(300, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        cuerpo.add(bEleminarIngrediente, gridBagConstraints);

        bModificarIngrediente.setFont(new java.awt.Font("Arial", 1, 14));
        bModificarIngrediente.setForeground(new java.awt.Color(80, 98, 143));
        bModificarIngrediente.setText("Modificar Ingrediente");
        bModificarIngrediente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bModificarIngrediente.setMaximumSize(new java.awt.Dimension(300, 200));
        bModificarIngrediente.setMinimumSize(new java.awt.Dimension(300, 200));
        bModificarIngrediente.setPreferredSize(new java.awt.Dimension(300, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        cuerpo.add(bModificarIngrediente, gridBagConstraints);

        bNotificarIncidente.setFont(new java.awt.Font("Arial", 1, 14));
        bNotificarIncidente.setForeground(new java.awt.Color(80, 98, 143));
        bNotificarIncidente.setText("Notificar Incidente");
        bNotificarIncidente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bNotificarIncidente.setMaximumSize(new java.awt.Dimension(300, 200));
        bNotificarIncidente.setMinimumSize(new java.awt.Dimension(300, 200));
        bNotificarIncidente.setPreferredSize(new java.awt.Dimension(300, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        cuerpo.add(bNotificarIncidente, gridBagConstraints);

        add(cuerpo, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton bAnadirIngrediente;
    protected javax.swing.JButton bEleminarIngrediente;
    protected javax.swing.JButton bModificarIngrediente;
    protected javax.swing.JButton bNotificarIncidente;
    protected javax.swing.JButton bVolver;
    private javax.swing.JPanel cabecera;
    private javax.swing.JPanel contenedorCentral;
    private javax.swing.JPanel contenedorDer;
    private javax.swing.JPanel contenedorIzq;
    private javax.swing.JPanel cuerpo;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables

}
