
package Vista.InterfazCocinero;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;

/**
 *
 * @author Daniel Guerrero Martinez
 */
public class IntColaCocinero extends javax.swing.JPanel {

    Integer pendientes = 0, preparandose = 0;
    
    /** Creates new form IntGestionCarta */
    public IntColaCocinero() {
        initComponents();
        this.setDoubleBuffered(true);
    }

    @Override
    public void paint(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();
        Rectangle clip = g2.getClipBounds();
        g2.setPaint(new GradientPaint(0.0f, 0.0f, new Color(170, 192, 249) ,getWidth() ,getHeight(), new Color(255, 255, 255) ));
        g2.fillRect(clip.x, clip.y, clip.width, clip.height);
        super.paint(g);
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        principalNorte = new javax.swing.JPanel();
        botonGestionProductos = new javax.swing.JButton();
        panelHora = new javax.swing.JPanel();
        labelHora = new javax.swing.JLabel();
        labelDia = new javax.swing.JLabel();
        principalIzquierda = new javax.swing.JPanel();
        principalDerecha = new javax.swing.JPanel();
        principalSur = new javax.swing.JPanel();
        principalCentro = new javax.swing.JPanel();
        panelIzquierda = new javax.swing.JPanel();
        infoPendientes = new javax.swing.JLabel();
        centro = new javax.swing.JPanel();
        panelDerecha = new javax.swing.JPanel();
        infoPreparandose = new javax.swing.JLabel();
        centroPreparandose = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout(15, 15));

        principalNorte.setOpaque(false);
        principalNorte.setLayout(new java.awt.BorderLayout());

        botonGestionProductos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonGestionProductos.setForeground(new java.awt.Color(80, 98, 143));
        botonGestionProductos.setText("Gestión de Productos");
        botonGestionProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionProductosActionPerformed(evt);
            }
        });
        principalNorte.add(botonGestionProductos, java.awt.BorderLayout.WEST);

        panelHora.setBackground(new java.awt.Color(255, 255, 255));
        panelHora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 172, 229), 3));
        panelHora.setLayout(new java.awt.GridBagLayout());

        labelHora.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        labelHora.setText("12:36");
        panelHora.add(labelHora, new java.awt.GridBagConstraints());

        labelDia.setFont(new java.awt.Font("Arial", 0, 11));
        labelDia.setText("Martes 12, Agosto 2010");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        panelHora.add(labelDia, gridBagConstraints);

        principalNorte.add(panelHora, java.awt.BorderLayout.EAST);

        add(principalNorte, java.awt.BorderLayout.PAGE_START);

        principalIzquierda.setOpaque(false);
        add(principalIzquierda, java.awt.BorderLayout.EAST);

        principalDerecha.setOpaque(false);
        add(principalDerecha, java.awt.BorderLayout.WEST);

        principalSur.setOpaque(false);
        principalSur.setPreferredSize(new java.awt.Dimension(1, 1));
        add(principalSur, java.awt.BorderLayout.SOUTH);

        principalCentro.setOpaque(false);
        principalCentro.setLayout(new java.awt.GridLayout(1, 0, 15, 0));

        panelIzquierda.setBackground(new java.awt.Color(245, 245, 255));
        panelIzquierda.setLayout(new java.awt.BorderLayout());

        infoPendientes.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        infoPendientes.setForeground(new java.awt.Color(80, 98, 143));
        infoPendientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoPendientes.setText("7 Platos Pendientes");
        infoPendientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 172, 229), 5));
        infoPendientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelIzquierda.add(infoPendientes, java.awt.BorderLayout.SOUTH);

        centro.setBackground(new java.awt.Color(245, 245, 255));
        centro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 172, 229), 5));
        panelIzquierda.add(centro, java.awt.BorderLayout.CENTER);

        principalCentro.add(panelIzquierda);

        panelDerecha.setBackground(new java.awt.Color(245, 245, 255));
        panelDerecha.setLayout(new java.awt.BorderLayout());

        infoPreparandose.setFont(new java.awt.Font("Arial", 1, 16));
        infoPreparandose.setForeground(new java.awt.Color(80, 98, 143));
        infoPreparandose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoPreparandose.setText("5 Platos Preparándose");
        infoPreparandose.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 172, 229), 5));
        panelDerecha.add(infoPreparandose, java.awt.BorderLayout.SOUTH);

        centroPreparandose.setBackground(new java.awt.Color(245, 245, 255));
        centroPreparandose.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 172, 229), 5));
        panelDerecha.add(centroPreparandose, java.awt.BorderLayout.CENTER);

        principalCentro.add(panelDerecha);

        add(principalCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void botonGestionProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGestionProductosActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                javax.swing.JDialog dialog = new javax.swing.JDialog(new javax.swing.JFrame(), true);
                dialog.setSize(800, 600);
                dialog.getContentPane().add(new IntColaCocinero(), java.awt.BorderLayout.CENTER);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGestionProductos;
    private javax.swing.JPanel centro;
    private javax.swing.JPanel centroPreparandose;
    private javax.swing.JLabel infoPendientes;
    private javax.swing.JLabel infoPreparandose;
    private javax.swing.JLabel labelDia;
    private javax.swing.JLabel labelHora;
    private javax.swing.JPanel panelDerecha;
    private javax.swing.JPanel panelHora;
    private javax.swing.JPanel panelIzquierda;
    private javax.swing.JPanel principalCentro;
    private javax.swing.JPanel principalDerecha;
    private javax.swing.JPanel principalIzquierda;
    private javax.swing.JPanel principalNorte;
    private javax.swing.JPanel principalSur;
    // End of variables declaration//GEN-END:variables


    private void setInfoPendientes(int n){
        String text = String.valueOf(n) + " platos pendientes";
        this.infoPendientes.setText(text);
    }
    private void setInfoPreparandose(int n){
        String text = String.valueOf(n) + " platos preparándose";
        this.infoPreparandose.setText(text);
    }
    private void ActualizarVista(){
        this.setInfoPendientes();
        this.setInfoPreparandose();
    }
}
