
package Vista.InterfazCocinero;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;

/**
 *
 * @author Daniel Guerrero Martinez
 */
public class IntGestionCarta extends javax.swing.JPanel {

    /** Creates new form IntGestionCarta */
    public IntGestionCarta() {
        initComponents();
        this.setDoubleBuffered(true);
    }

    @Override
    public void paint(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();
        Rectangle clip = g2.getClipBounds();
        g2.setPaint(new GradientPaint(0.0f, 0.0f, new Color(170, 192, 249) ,getWidth() ,getHeight(), new Color(255, 255, 255) ));
        g2.fillRect(clip.x, clip.y, clip.width, clip.height);
        super.paint(g);
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        cabecera = new javax.swing.JPanel();
        contenedorDer = new javax.swing.JPanel();
        contenedorIzq = new javax.swing.JPanel();
        bVolver = new javax.swing.JButton();
        contenedorCentral = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        cuerpo = new javax.swing.JPanel();
        bAnadirElemento = new javax.swing.JButton();
        bEleminarElemento = new javax.swing.JButton();
        bModificarElemento = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        cabecera.setMinimumSize(new java.awt.Dimension(50, 50));
        cabecera.setOpaque(false);
        cabecera.setLayout(new java.awt.BorderLayout());

        contenedorDer.setOpaque(false);
        contenedorDer.setPreferredSize(new java.awt.Dimension(200, 100));
        contenedorDer.setLayout(new java.awt.GridBagLayout());
        cabecera.add(contenedorDer, java.awt.BorderLayout.EAST);

        contenedorIzq.setOpaque(false);
        contenedorIzq.setPreferredSize(new java.awt.Dimension(200, 100));
        contenedorIzq.setLayout(new java.awt.GridBagLayout());

        bVolver.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        bVolver.setForeground(new java.awt.Color(80, 98, 143));
        bVolver.setText("Volver");
        bVolver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bVolver.setPreferredSize(new java.awt.Dimension(100, 50));
        contenedorIzq.add(bVolver, new java.awt.GridBagConstraints());

        cabecera.add(contenedorIzq, java.awt.BorderLayout.WEST);

        contenedorCentral.setOpaque(false);
        contenedorCentral.setLayout(new java.awt.GridBagLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/InterfazCocinero/imagenes/LogoSagres.png"))); // NOI18N
        logo.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/InterfazCocinero/imagenes/LogoSagres.png"))); // NOI18N
        contenedorCentral.add(logo, new java.awt.GridBagConstraints());

        cabecera.add(contenedorCentral, java.awt.BorderLayout.CENTER);

        add(cabecera, java.awt.BorderLayout.PAGE_START);

        cuerpo.setMinimumSize(new java.awt.Dimension(800, 600));
        cuerpo.setOpaque(false);
        cuerpo.setLayout(new java.awt.GridBagLayout());

        bAnadirElemento.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        bAnadirElemento.setForeground(new java.awt.Color(80, 98, 143));
        bAnadirElemento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/InterfazCocinero/imagenes/anadirElemento.png"))); // NOI18N
        bAnadirElemento.setText("Añadir elemento");
        bAnadirElemento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bAnadirElemento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bAnadirElemento.setMaximumSize(new java.awt.Dimension(300, 200));
        bAnadirElemento.setMinimumSize(new java.awt.Dimension(300, 200));
        bAnadirElemento.setPreferredSize(new java.awt.Dimension(300, 200));
        bAnadirElemento.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        cuerpo.add(bAnadirElemento, gridBagConstraints);

        bEleminarElemento.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        bEleminarElemento.setForeground(new java.awt.Color(80, 98, 143));
        bEleminarElemento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/InterfazCocinero/imagenes/EliminarElemento.png"))); // NOI18N
        bEleminarElemento.setText("Eliminar elemento");
        bEleminarElemento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bEleminarElemento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bEleminarElemento.setMaximumSize(new java.awt.Dimension(300, 200));
        bEleminarElemento.setMinimumSize(new java.awt.Dimension(300, 200));
        bEleminarElemento.setPreferredSize(new java.awt.Dimension(300, 200));
        bEleminarElemento.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        cuerpo.add(bEleminarElemento, gridBagConstraints);

        bModificarElemento.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        bModificarElemento.setForeground(new java.awt.Color(80, 98, 143));
        bModificarElemento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/InterfazCocinero/imagenes/ModificarElemento.png"))); // NOI18N
        bModificarElemento.setText("Modificar elemento");
        bModificarElemento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bModificarElemento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bModificarElemento.setMaximumSize(new java.awt.Dimension(300, 200));
        bModificarElemento.setMinimumSize(new java.awt.Dimension(300, 200));
        bModificarElemento.setPreferredSize(new java.awt.Dimension(300, 200));
        bModificarElemento.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        cuerpo.add(bModificarElemento, gridBagConstraints);

        add(cuerpo, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton bAnadirElemento;
    protected javax.swing.JButton bEleminarElemento;
    protected javax.swing.JButton bModificarElemento;
    protected javax.swing.JButton bVolver;
    private javax.swing.JPanel cabecera;
    private javax.swing.JPanel contenedorCentral;
    private javax.swing.JPanel contenedorDer;
    private javax.swing.JPanel contenedorIzq;
    private javax.swing.JPanel cuerpo;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables

}
