/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelPedidoPorMesa.java
 *
 * Created on 08-may-2010, 18:11:19
 */

package utilidades;

import javax.swing.JButton;

/**
 *
 * @author redder
 */
public class PanelPedidoPorMesa extends javax.swing.JPanel {

    /** Creates new form PanelPedidoPorMesa */
    public PanelPedidoPorMesa() {
        initComponents();
        for(int i=0; i<4; ++i){
            JButton b = new JButton("Boton "+i);
            b.setBackground(new java.awt.Color(211, 223, 253));
            b.setFont(new java.awt.Font("Arial", 0, 10));
            b.setForeground(new java.awt.Color(80, 98, 143));
            b.setText("<html>\n<body> \nHamburguesa con queso \n<br></br>\n<br></br>\n<font color=\"#000000\">La carne poco hecha, por favor...</font>\n</body>\n</html>\n");
            b.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            pPedidos.add(b);
            this.pPedidos.add(new PanelEspacioVertical());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pTexto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pPedidos = new javax.swing.JPanel();
        pEspacioIzq = new javax.swing.JPanel();
        pEspacioDer = new javax.swing.JPanel();

        setBackground(new java.awt.Color(235, 235, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 172, 229), 3));
        setLayout(new java.awt.BorderLayout());

        pTexto.setOpaque(false);
        pTexto.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(80, 98, 143));
        jLabel1.setText("     Mesa 5, Pedido 2");
        jLabel1.setPreferredSize(new java.awt.Dimension(92, 35));
        pTexto.add(jLabel1, java.awt.BorderLayout.CENTER);

        add(pTexto, java.awt.BorderLayout.NORTH);

        pPedidos.setOpaque(false);
        pPedidos.setLayout(new javax.swing.BoxLayout(pPedidos, javax.swing.BoxLayout.Y_AXIS));
        add(pPedidos, java.awt.BorderLayout.CENTER);

        pEspacioIzq.setMaximumSize(new java.awt.Dimension(5, 0));
        pEspacioIzq.setMinimumSize(new java.awt.Dimension(5, 0));
        pEspacioIzq.setOpaque(false);
        pEspacioIzq.setPreferredSize(new java.awt.Dimension(5, 0));

        javax.swing.GroupLayout pEspacioIzqLayout = new javax.swing.GroupLayout(pEspacioIzq);
        pEspacioIzq.setLayout(pEspacioIzqLayout);
        pEspacioIzqLayout.setHorizontalGroup(
            pEspacioIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pEspacioIzqLayout.setVerticalGroup(
            pEspacioIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 259, Short.MAX_VALUE)
        );

        add(pEspacioIzq, java.awt.BorderLayout.WEST);

        pEspacioDer.setMaximumSize(new java.awt.Dimension(5, 0));
        pEspacioDer.setMinimumSize(new java.awt.Dimension(5, 0));
        pEspacioDer.setOpaque(false);
        pEspacioDer.setPreferredSize(new java.awt.Dimension(5, 0));

        javax.swing.GroupLayout pEspacioDerLayout = new javax.swing.GroupLayout(pEspacioDer);
        pEspacioDer.setLayout(pEspacioDerLayout);
        pEspacioDerLayout.setHorizontalGroup(
            pEspacioDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pEspacioDerLayout.setVerticalGroup(
            pEspacioDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 259, Short.MAX_VALUE)
        );

        add(pEspacioDer, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pEspacioDer;
    private javax.swing.JPanel pEspacioIzq;
    private javax.swing.JPanel pPedidos;
    private javax.swing.JPanel pTexto;
    // End of variables declaration//GEN-END:variables

}
