/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelPrincipalCliente.java
 *
 * Created on 04-may-2010, 16:38:03
 */

package Vista.InterfazCliente;

/**
 *
 * @author Carlos
 */
public class PanelPrincipalCliente extends javax.swing.JPanel {

    /** Creates new form PanelPrincipalCliente */
    public PanelPrincipalCliente() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGeneralEste = new javax.swing.JPanel();
        PanelPedido = new javax.swing.JPanel();
        PanelPedidoComida = new javax.swing.JPanel();
        PanelPedidoBebida = new javax.swing.JPanel();
        BotonVerFactura = new javax.swing.JButton();
        PanelGeneralCentro = new javax.swing.JPanel();
        PanelComentarios = new javax.swing.JPanel();
        PanelCartaBotones = new javax.swing.JPanel();
        PanelCarta = new javax.swing.JPanel();
        PanelBotones = new javax.swing.JPanel();
        BotonEntrantes = new javax.swing.JButton();
        BotonPescados = new javax.swing.JButton();
        BotonCarnes = new javax.swing.JButton();
        BotonBebidas = new javax.swing.JButton();
        BotonPostres = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        PanelGeneralEste.setLayout(new java.awt.BorderLayout());

        PanelPedido.setLayout(new java.awt.BorderLayout());

        PanelPedidoComida.setLayout(new java.awt.BorderLayout());
        PanelPedido.add(PanelPedidoComida, java.awt.BorderLayout.CENTER);

        PanelPedidoBebida.setLayout(new java.awt.BorderLayout());
        PanelPedido.add(PanelPedidoBebida, java.awt.BorderLayout.PAGE_START);

        PanelGeneralEste.add(PanelPedido, java.awt.BorderLayout.CENTER);

        BotonVerFactura.setText("Ver Factura");
        BotonVerFactura.setPreferredSize(new java.awt.Dimension(89, 50));
        PanelGeneralEste.add(BotonVerFactura, java.awt.BorderLayout.SOUTH);

        add(PanelGeneralEste, java.awt.BorderLayout.EAST);

        PanelGeneralCentro.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout PanelComentariosLayout = new javax.swing.GroupLayout(PanelComentarios);
        PanelComentarios.setLayout(PanelComentariosLayout);
        PanelComentariosLayout.setHorizontalGroup(
            PanelComentariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        PanelComentariosLayout.setVerticalGroup(
            PanelComentariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        PanelGeneralCentro.add(PanelComentarios, java.awt.BorderLayout.PAGE_END);

        PanelCartaBotones.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout PanelCartaLayout = new javax.swing.GroupLayout(PanelCarta);
        PanelCarta.setLayout(PanelCartaLayout);
        PanelCartaLayout.setHorizontalGroup(
            PanelCartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        PanelCartaLayout.setVerticalGroup(
            PanelCartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 177, Short.MAX_VALUE)
        );

        PanelCartaBotones.add(PanelCarta, java.awt.BorderLayout.CENTER);

        PanelBotones.setLayout(new java.awt.GridLayout(0, 5));

        BotonEntrantes.setText("Entrantes");
        PanelBotones.add(BotonEntrantes);

        BotonPescados.setText("Pescados");
        PanelBotones.add(BotonPescados);

        BotonCarnes.setText("Carnes");
        PanelBotones.add(BotonCarnes);

        BotonBebidas.setText("Bebidas");
        PanelBotones.add(BotonBebidas);

        BotonPostres.setText("Postres");
        PanelBotones.add(BotonPostres);

        PanelCartaBotones.add(PanelBotones, java.awt.BorderLayout.SOUTH);

        PanelGeneralCentro.add(PanelCartaBotones, java.awt.BorderLayout.CENTER);

        add(PanelGeneralCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBebidas;
    private javax.swing.JButton BotonCarnes;
    private javax.swing.JButton BotonEntrantes;
    private javax.swing.JButton BotonPescados;
    private javax.swing.JButton BotonPostres;
    private javax.swing.JButton BotonVerFactura;
    private javax.swing.JPanel PanelBotones;
    private javax.swing.JPanel PanelCarta;
    private javax.swing.JPanel PanelCartaBotones;
    private javax.swing.JPanel PanelComentarios;
    private javax.swing.JPanel PanelGeneralCentro;
    private javax.swing.JPanel PanelGeneralEste;
    private javax.swing.JPanel PanelPedido;
    private javax.swing.JPanel PanelPedidoBebida;
    private javax.swing.JPanel PanelPedidoComida;
    // End of variables declaration//GEN-END:variables

}
