/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelListaPedido.java
 *
 * Created on 11-may-2010, 17:42:46
 */

package Vista.InterfazCliente;

import GestionCarta.Elemento;
import GestionCarta.ElementoPlato;
import java.util.ArrayList;
import java.util.Iterator;

/**
 *
 * @author Carlos
 */
public class PanelListaPedido extends javax.swing.JPanel {

    PanelGeneralCliente PGC;

    /** Creates new form PanelListaPedido */
    public PanelListaPedido(ArrayList<Elemento> listaElementos, PanelGeneralCliente PGC) {
        initComponents();

        this.PGC=PGC;

        this.TextoListaComida.setText("");
        this.TextoListaBebida.setText("");
        
        Iterator it = listaElementos.iterator();

        while(it.hasNext()){
            Elemento elemento = (Elemento) it.next();

            if(elemento instanceof ElementoPlato){
                this.TextoListaComida.setText(this.TextoListaComida.getText()+"\n- "+elemento.getNombre());
            }else{
                this.TextoListaBebida.setText(this.TextoListaBebida.getText()+"\n- "+elemento.getNombre());
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelListaComida = new javax.swing.JPanel();
        ScrollListaComida = new javax.swing.JScrollPane();
        TextoListaComida = new javax.swing.JTextPane();
        BotonModificar = new javax.swing.JButton();
        PanelListaBebida = new javax.swing.JPanel();
        ScrollBebida = new javax.swing.JScrollPane();
        TextoListaBebida = new javax.swing.JEditorPane();

        setLayout(new java.awt.BorderLayout());

        PanelListaComida.setLayout(new java.awt.BorderLayout());

        TextoListaComida.setEditable(false);
        ScrollListaComida.setViewportView(TextoListaComida);

        PanelListaComida.add(ScrollListaComida, java.awt.BorderLayout.CENTER);

        BotonModificar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        BotonModificar.setForeground(new java.awt.Color(80, 98, 143));
        BotonModificar.setText("Modificar");
        BotonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarPedido(evt);
            }
        });
        PanelListaComida.add(BotonModificar, java.awt.BorderLayout.PAGE_END);

        add(PanelListaComida, java.awt.BorderLayout.CENTER);

        PanelListaBebida.setLayout(new java.awt.BorderLayout());

        ScrollBebida.setViewportView(TextoListaBebida);

        PanelListaBebida.add(ScrollBebida, java.awt.BorderLayout.CENTER);

        add(PanelListaBebida, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void modificarPedido(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarPedido
        this.PGC.iniciaModificaPedido();
    }//GEN-LAST:event_modificarPedido


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonModificar;
    private javax.swing.JPanel PanelListaBebida;
    private javax.swing.JPanel PanelListaComida;
    private javax.swing.JScrollPane ScrollBebida;
    private javax.swing.JScrollPane ScrollListaComida;
    private javax.swing.JEditorPane TextoListaBebida;
    private javax.swing.JTextPane TextoListaComida;
    // End of variables declaration//GEN-END:variables

}
