/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelHojasCarta.java
 *
 * Created on 04-may-2010, 16:58:06
 */

package Vista.InterfazCliente;

import ControladorPrincipal.ICliente;
import GestionCarta.Elemento;
import Vista.InterfazCliente.PanelElementoCarta;
import java.awt.BorderLayout;
import java.awt.Image;
import java.util.HashSet;
import java.util.Iterator;

/**
 *
 * @author Carlos
 */
public class PanelHojasCarta extends javax.swing.JPanel {

    private ICliente icliente;

    /** Creates new form PanelHojasCarta */
    public PanelHojasCarta(HashSet<Elemento> listaElementos) throws Exception {
        initComponents();

        Iterator it = listaElementos.iterator();

        Elemento e;

        if(it.hasNext()){
            e = (Elemento) it.next();
            PanelElementoArribaI.add(new PanelElementoCarta(e));

            if(it.hasNext()){
                e = (Elemento) it.next();
                PanelElementoCentroI.add(new PanelElementoCarta(e));

                if(it.hasNext()){
                    e = (Elemento) it.next();
                    PanelElementoAbajoI.add(new PanelElementoCarta(e));

                    if(it.hasNext()){
                        e = (Elemento) it.next();
                        PanelElementoArribaD.add(new PanelElementoCarta(e));

                        if(it.hasNext()){
                            e = (Elemento) it.next();
                            PanelElementoCentroD.add(new PanelElementoCarta(e));

                            if(it.hasNext()){
                                e = (Elemento) it.next();
                                PanelElementoAbajoD.add(new PanelElementoCarta(e));
                            }
                        }
                    }
                }
            }
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelHojaDerecha = new javax.swing.JPanel();
        PanelElementoArribaD = new javax.swing.JPanel();
        PanelElementoCentroD = new javax.swing.JPanel();
        PanelElementoAbajoD = new javax.swing.JPanel();
        PanelHojaIzquierda = new javax.swing.JPanel();
        PanelElementoArribaI = new javax.swing.JPanel();
        PanelElementoCentroI = new javax.swing.JPanel();
        PanelElementoAbajoI = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout());

        PanelHojaDerecha.setLayout(new java.awt.GridLayout(3, 0));

        PanelElementoArribaD.setLayout(new java.awt.BorderLayout());
        PanelHojaDerecha.add(PanelElementoArribaD);

        PanelElementoCentroD.setLayout(new java.awt.BorderLayout());
        PanelHojaDerecha.add(PanelElementoCentroD);

        PanelElementoAbajoD.setLayout(new java.awt.BorderLayout());
        PanelHojaDerecha.add(PanelElementoAbajoD);

        add(PanelHojaDerecha);

        PanelHojaIzquierda.setLayout(new java.awt.GridLayout(3, 0));

        PanelElementoArribaI.setLayout(new java.awt.BorderLayout());
        PanelHojaIzquierda.add(PanelElementoArribaI);

        PanelElementoCentroI.setLayout(new java.awt.BorderLayout());
        PanelHojaIzquierda.add(PanelElementoCentroI);

        PanelElementoAbajoI.setLayout(new java.awt.BorderLayout());
        PanelHojaIzquierda.add(PanelElementoAbajoI);

        add(PanelHojaIzquierda);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelElementoAbajoD;
    private javax.swing.JPanel PanelElementoAbajoI;
    private javax.swing.JPanel PanelElementoArribaD;
    private javax.swing.JPanel PanelElementoArribaI;
    private javax.swing.JPanel PanelElementoCentroD;
    private javax.swing.JPanel PanelElementoCentroI;
    private javax.swing.JPanel PanelHojaDerecha;
    private javax.swing.JPanel PanelHojaIzquierda;
    // End of variables declaration//GEN-END:variables

}
