
package Vista.InterfazCocinero;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;

/**
 *
 * @author Daniel Guerrero Martinez
 */
public class IntPrincipalCocinero extends javax.swing.JPanel {

    /** Creates new form IntGestionCarta */
    public IntPrincipalCocinero() {
        initComponents();
        this.setDoubleBuffered(true);
    }

    @Override
    public void paint(Graphics g) {
        super.paintComponents(g);
        Graphics2D g2 = (Graphics2D) g.create();
        Rectangle clip = g2.getClipBounds();
        g2.setPaint(new GradientPaint(0.0f, 0.0f, new Color(170, 192, 249) ,getWidth() ,getHeight(), new Color(255, 255, 255) ));
        g2.fillRect(clip.x, clip.y, clip.width, clip.height);
        super.paint(g);
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        cabecera = new javax.swing.JPanel();
        contenedorDer = new javax.swing.JPanel();
        contenedorIzq = new javax.swing.JPanel();
        bSalir = new javax.swing.JButton();
        contenedorCentral = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        cuerpo = new javax.swing.JPanel();
        bGestionCarta = new javax.swing.JButton();
        bNotificcarPedido = new javax.swing.JButton();
        bGestionIngredientes = new javax.swing.JButton();
        bEstaditicas = new javax.swing.JButton();
        bImprimirProductosaPedir = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        cabecera.setMinimumSize(new java.awt.Dimension(50, 50));
        cabecera.setOpaque(false);
        cabecera.setLayout(new java.awt.BorderLayout());

        contenedorDer.setOpaque(false);
        contenedorDer.setPreferredSize(new java.awt.Dimension(200, 100));
        contenedorDer.setLayout(new java.awt.GridBagLayout());
        cabecera.add(contenedorDer, java.awt.BorderLayout.EAST);

        contenedorIzq.setOpaque(false);
        contenedorIzq.setPreferredSize(new java.awt.Dimension(200, 100));
        contenedorIzq.setLayout(new java.awt.GridBagLayout());

        bSalir.setFont(new java.awt.Font("Arial", 1, 14));
        bSalir.setForeground(new java.awt.Color(80, 98, 143));
        bSalir.setText("Salir");
        bSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bSalir.setPreferredSize(new java.awt.Dimension(100, 50));
        contenedorIzq.add(bSalir, new java.awt.GridBagConstraints());

        cabecera.add(contenedorIzq, java.awt.BorderLayout.WEST);

        contenedorCentral.setOpaque(false);
        contenedorCentral.setLayout(new java.awt.GridBagLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/InterfazCocinero/imagenes/LogoSagres.png"))); // NOI18N
        logo.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/InterfazCocinero/imagenes/LogoSagres.png"))); // NOI18N
        contenedorCentral.add(logo, new java.awt.GridBagConstraints());

        cabecera.add(contenedorCentral, java.awt.BorderLayout.CENTER);

        add(cabecera, java.awt.BorderLayout.PAGE_START);

        cuerpo.setMinimumSize(new java.awt.Dimension(800, 600));
        cuerpo.setOpaque(false);
        cuerpo.setLayout(new java.awt.GridBagLayout());

        bGestionCarta.setFont(new java.awt.Font("Arial", 1, 14));
        bGestionCarta.setForeground(new java.awt.Color(80, 98, 143));
        bGestionCarta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/InterfazCocinero/imagenes/Libreta.png"))); // NOI18N
        bGestionCarta.setText("Gestión de carta");
        bGestionCarta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bGestionCarta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bGestionCarta.setMaximumSize(new java.awt.Dimension(300, 200));
        bGestionCarta.setMinimumSize(new java.awt.Dimension(300, 200));
        bGestionCarta.setPreferredSize(new java.awt.Dimension(300, 200));
        bGestionCarta.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        cuerpo.add(bGestionCarta, gridBagConstraints);

        bNotificcarPedido.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bNotificcarPedido.setForeground(new java.awt.Color(80, 98, 143));
        bNotificcarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/InterfazCocinero/imagenes/NotificarLlegada.png"))); // NOI18N
        bNotificcarPedido.setText("Notificar recepción de pedido");
        bNotificcarPedido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bNotificcarPedido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bNotificcarPedido.setMaximumSize(new java.awt.Dimension(300, 200));
        bNotificcarPedido.setMinimumSize(new java.awt.Dimension(300, 200));
        bNotificcarPedido.setPreferredSize(new java.awt.Dimension(300, 200));
        bNotificcarPedido.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        cuerpo.add(bNotificcarPedido, gridBagConstraints);

        bGestionIngredientes.setFont(new java.awt.Font("Arial", 1, 14));
        bGestionIngredientes.setForeground(new java.awt.Color(80, 98, 143));
        bGestionIngredientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/InterfazCocinero/imagenes/GestionIngredientes.png"))); // NOI18N
        bGestionIngredientes.setText("Gestión de Ingredientes");
        bGestionIngredientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bGestionIngredientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bGestionIngredientes.setMaximumSize(new java.awt.Dimension(300, 200));
        bGestionIngredientes.setMinimumSize(new java.awt.Dimension(300, 200));
        bGestionIngredientes.setPreferredSize(new java.awt.Dimension(300, 200));
        bGestionIngredientes.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        cuerpo.add(bGestionIngredientes, gridBagConstraints);

        bEstaditicas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bEstaditicas.setForeground(new java.awt.Color(80, 98, 143));
        bEstaditicas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/InterfazCocinero/imagenes/Estadisticas.png"))); // NOI18N
        bEstaditicas.setText("Estadisticas");
        bEstaditicas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bEstaditicas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bEstaditicas.setMaximumSize(new java.awt.Dimension(300, 200));
        bEstaditicas.setMinimumSize(new java.awt.Dimension(300, 200));
        bEstaditicas.setPreferredSize(new java.awt.Dimension(300, 200));
        bEstaditicas.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        cuerpo.add(bEstaditicas, gridBagConstraints);

        bImprimirProductosaPedir.setFont(new java.awt.Font("Arial", 1, 14));
        bImprimirProductosaPedir.setForeground(new java.awt.Color(80, 98, 143));
        bImprimirProductosaPedir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/InterfazCocinero/imagenes/ImprimirLista.png"))); // NOI18N
        bImprimirProductosaPedir.setText("Imprimir productos a pedir");
        bImprimirProductosaPedir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bImprimirProductosaPedir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bImprimirProductosaPedir.setMaximumSize(new java.awt.Dimension(300, 200));
        bImprimirProductosaPedir.setMinimumSize(new java.awt.Dimension(300, 200));
        bImprimirProductosaPedir.setPreferredSize(new java.awt.Dimension(300, 200));
        bImprimirProductosaPedir.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        cuerpo.add(bImprimirProductosaPedir, gridBagConstraints);

        add(cuerpo, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton bEstaditicas;
    protected javax.swing.JButton bGestionCarta;
    protected javax.swing.JButton bGestionIngredientes;
    protected javax.swing.JButton bImprimirProductosaPedir;
    protected javax.swing.JButton bNotificcarPedido;
    protected javax.swing.JButton bSalir;
    private javax.swing.JPanel cabecera;
    private javax.swing.JPanel contenedorCentral;
    private javax.swing.JPanel contenedorDer;
    private javax.swing.JPanel contenedorIzq;
    private javax.swing.JPanel cuerpo;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables

}
