/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IntColaBar.java
 *
 * Created on 06-may-2010, 11:40:36
 */

package Vista.InterfazMetre;

import ControladorPrincipal.IMetre;
import utilidades.PanelRelojFecha;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import utilidades.HebraBar;
import utilidades.PanelMesaPedido;

/**
 *
 * @author Samuel Guirado Navarro
 */
public class IntColaBar extends javax.swing.JPanel {

    public PanelMesaPedido pmp = null;
    public PanelColaFacturas colaIzq = null;
    public PanelColaFacturas colaDer = null;
    private HebraBar hebra;
    public IMetre imetre;
    public InterfazMetre ventana;
    
    /** Creates new form IntColaBar */
    public IntColaBar(IMetre imetre, InterfazMetre ventana) {
        initComponents();
        this.imetre = imetre;
        this.ventana = ventana;
        pmp = new PanelMesaPedido(imetre, ventana);
        colaIzq = new PanelColaFacturas(ventana,PanelColaFacturas.PARAIMPRIMIR);
        colaDer = new PanelColaFacturas(ventana,PanelColaFacturas.PARAFACTURAR);
        
        pDer.add(new PanelRelojFecha(), java.awt.BorderLayout.CENTER);
        pIzq2.add(pmp,java.awt.BorderLayout.CENTER);
        
        centroIzq.add(colaIzq, java.awt.BorderLayout.CENTER);
        centroDer.add(colaDer, java.awt.BorderLayout.CENTER);

        this.hebra = new HebraBar(pmp, colaIzq, colaDer, ventana);
    }

    @Override
    public void paint(Graphics g) {
        super.paintComponents(g);
        Graphics2D g2 = (Graphics2D) g.create();
        Rectangle clip = g2.getClipBounds();
        g2.setPaint(new GradientPaint(0.0f, 0.0f, new Color(30, 40, 90) ,getWidth() ,getHeight(), new Color(155, 155, 200) ));
        g2.fillRect(clip.x, clip.y, clip.width, clip.height);
        super.paint(g);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        margenInf = new javax.swing.JPanel();
        margenSup = new javax.swing.JPanel();
        pCentroCabeceraCuerpo = new javax.swing.JPanel();
        cabecera = new javax.swing.JPanel();
        pDer = new javax.swing.JPanel();
        pIzq = new javax.swing.JPanel();
        bGestBebidas = new javax.swing.JButton();
        pCentro = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        cuerpo = new javax.swing.JPanel();
        pIzq2 = new javax.swing.JPanel();
        margenInf2 = new javax.swing.JPanel();
        margenSup1 = new javax.swing.JPanel();
        margenDer2 = new javax.swing.JPanel();
        margenIzq2 = new javax.swing.JPanel();
        pDer2 = new javax.swing.JPanel();
        margenInf1 = new javax.swing.JPanel();
        margenDer1 = new javax.swing.JPanel();
        margenIzq1 = new javax.swing.JPanel();
        centro = new javax.swing.JPanel();
        centroIzq = new javax.swing.JPanel();
        panelTextoIzq = new javax.swing.JPanel();
        textoIzq = new javax.swing.JLabel();
        centroDer = new javax.swing.JPanel();
        panelTextoDer = new javax.swing.JPanel();
        textoDer = new javax.swing.JLabel();
        margenDer = new javax.swing.JPanel();
        margenIzq = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 650));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.BorderLayout());

        margenInf.setOpaque(false);

        javax.swing.GroupLayout margenInfLayout = new javax.swing.GroupLayout(margenInf);
        margenInf.setLayout(margenInfLayout);
        margenInfLayout.setHorizontalGroup(
            margenInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        margenInfLayout.setVerticalGroup(
            margenInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        add(margenInf, java.awt.BorderLayout.SOUTH);

        margenSup.setOpaque(false);

        javax.swing.GroupLayout margenSupLayout = new javax.swing.GroupLayout(margenSup);
        margenSup.setLayout(margenSupLayout);
        margenSupLayout.setHorizontalGroup(
            margenSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        margenSupLayout.setVerticalGroup(
            margenSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        add(margenSup, java.awt.BorderLayout.NORTH);

        pCentroCabeceraCuerpo.setOpaque(false);
        pCentroCabeceraCuerpo.setLayout(new java.awt.BorderLayout());

        cabecera.setMinimumSize(new java.awt.Dimension(50, 50));
        cabecera.setOpaque(false);
        cabecera.setPreferredSize(new java.awt.Dimension(500, 100));
        cabecera.setLayout(new java.awt.BorderLayout());

        pDer.setMaximumSize(new java.awt.Dimension(230, 100));
        pDer.setMinimumSize(new java.awt.Dimension(230, 100));
        pDer.setOpaque(false);
        pDer.setPreferredSize(new java.awt.Dimension(230, 100));
        pDer.setLayout(new java.awt.BorderLayout());
        cabecera.add(pDer, java.awt.BorderLayout.EAST);

        pIzq.setMinimumSize(new java.awt.Dimension(35, 21));
        pIzq.setOpaque(false);
        pIzq.setPreferredSize(new java.awt.Dimension(200, 100));
        pIzq.setLayout(new java.awt.BorderLayout());

        bGestBebidas.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        bGestBebidas.setForeground(new java.awt.Color(80, 98, 143));
        bGestBebidas.setText("<html><body>Gestionar<br> Bebidas</html></body>");
        bGestBebidas.setActionCommand("GestProductos");
        bGestBebidas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 172, 229), 3));
        bGestBebidas.setMaximumSize(new java.awt.Dimension(200, 80));
        bGestBebidas.setMinimumSize(new java.awt.Dimension(200, 80));
        bGestBebidas.setPreferredSize(new java.awt.Dimension(200, 80));
        pIzq.add(bGestBebidas, java.awt.BorderLayout.CENTER);
        bGestBebidas.getAccessibleContext().setAccessibleName("");

        cabecera.add(pIzq, java.awt.BorderLayout.WEST);

        pCentro.setOpaque(false);
        pCentro.setLayout(new java.awt.BorderLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/InterfazMetre/imagenes/LogoSagres.png"))); // NOI18N
        pCentro.add(logo, java.awt.BorderLayout.CENTER);

        cabecera.add(pCentro, java.awt.BorderLayout.CENTER);

        pCentroCabeceraCuerpo.add(cabecera, java.awt.BorderLayout.NORTH);

        cuerpo.setOpaque(false);
        cuerpo.setLayout(new java.awt.GridLayout(1, 2));

        pIzq2.setOpaque(false);
        pIzq2.setLayout(new java.awt.BorderLayout());

        margenInf2.setOpaque(false);
        margenInf2.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout margenInf2Layout = new javax.swing.GroupLayout(margenInf2);
        margenInf2.setLayout(margenInf2Layout);
        margenInf2Layout.setHorizontalGroup(
            margenInf2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        margenInf2Layout.setVerticalGroup(
            margenInf2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pIzq2.add(margenInf2, java.awt.BorderLayout.SOUTH);

        margenSup1.setOpaque(false);
        margenSup1.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout margenSup1Layout = new javax.swing.GroupLayout(margenSup1);
        margenSup1.setLayout(margenSup1Layout);
        margenSup1Layout.setHorizontalGroup(
            margenSup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        margenSup1Layout.setVerticalGroup(
            margenSup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pIzq2.add(margenSup1, java.awt.BorderLayout.NORTH);

        margenDer2.setOpaque(false);
        margenDer2.setPreferredSize(new java.awt.Dimension(10, 10));

        javax.swing.GroupLayout margenDer2Layout = new javax.swing.GroupLayout(margenDer2);
        margenDer2.setLayout(margenDer2Layout);
        margenDer2Layout.setHorizontalGroup(
            margenDer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        margenDer2Layout.setVerticalGroup(
            margenDer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        pIzq2.add(margenDer2, java.awt.BorderLayout.EAST);

        margenIzq2.setOpaque(false);
        margenIzq2.setPreferredSize(new java.awt.Dimension(10, 10));

        javax.swing.GroupLayout margenIzq2Layout = new javax.swing.GroupLayout(margenIzq2);
        margenIzq2.setLayout(margenIzq2Layout);
        margenIzq2Layout.setHorizontalGroup(
            margenIzq2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        margenIzq2Layout.setVerticalGroup(
            margenIzq2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        pIzq2.add(margenIzq2, java.awt.BorderLayout.WEST);

        cuerpo.add(pIzq2);

        pDer2.setOpaque(false);
        pDer2.setLayout(new java.awt.BorderLayout());

        margenInf1.setOpaque(false);
        margenInf1.setPreferredSize(new java.awt.Dimension(400, 30));

        javax.swing.GroupLayout margenInf1Layout = new javax.swing.GroupLayout(margenInf1);
        margenInf1.setLayout(margenInf1Layout);
        margenInf1Layout.setHorizontalGroup(
            margenInf1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        margenInf1Layout.setVerticalGroup(
            margenInf1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        pDer2.add(margenInf1, java.awt.BorderLayout.SOUTH);

        margenDer1.setOpaque(false);
        margenDer1.setPreferredSize(new java.awt.Dimension(20, 500));

        javax.swing.GroupLayout margenDer1Layout = new javax.swing.GroupLayout(margenDer1);
        margenDer1.setLayout(margenDer1Layout);
        margenDer1Layout.setHorizontalGroup(
            margenDer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        margenDer1Layout.setVerticalGroup(
            margenDer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        pDer2.add(margenDer1, java.awt.BorderLayout.EAST);

        margenIzq1.setOpaque(false);
        margenIzq1.setPreferredSize(new java.awt.Dimension(20, 350));

        javax.swing.GroupLayout margenIzq1Layout = new javax.swing.GroupLayout(margenIzq1);
        margenIzq1.setLayout(margenIzq1Layout);
        margenIzq1Layout.setHorizontalGroup(
            margenIzq1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        margenIzq1Layout.setVerticalGroup(
            margenIzq1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        pDer2.add(margenIzq1, java.awt.BorderLayout.WEST);

        centro.setOpaque(false);
        centro.setLayout(new java.awt.GridLayout(1, 2, 25, 0));

        centroIzq.setOpaque(false);
        centroIzq.setLayout(new java.awt.BorderLayout());

        panelTextoIzq.setOpaque(false);
        panelTextoIzq.setPreferredSize(new java.awt.Dimension(180, 20));
        panelTextoIzq.setLayout(new java.awt.BorderLayout());

        textoIzq.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        textoIzq.setForeground(new java.awt.Color(150, 172, 229));
        textoIzq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoIzq.setText("Facturas a imprimir");
        panelTextoIzq.add(textoIzq, java.awt.BorderLayout.CENTER);

        centroIzq.add(panelTextoIzq, java.awt.BorderLayout.NORTH);

        centro.add(centroIzq);

        centroDer.setOpaque(false);
        centroDer.setLayout(new java.awt.BorderLayout());

        panelTextoDer.setOpaque(false);
        panelTextoDer.setPreferredSize(new java.awt.Dimension(180, 20));
        panelTextoDer.setLayout(new java.awt.BorderLayout());

        textoDer.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        textoDer.setForeground(new java.awt.Color(150, 172, 229));
        textoDer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoDer.setText("Mesas por facturar");
        panelTextoDer.add(textoDer, java.awt.BorderLayout.CENTER);

        centroDer.add(panelTextoDer, java.awt.BorderLayout.NORTH);

        centro.add(centroDer);

        pDer2.add(centro, java.awt.BorderLayout.CENTER);

        cuerpo.add(pDer2);

        pCentroCabeceraCuerpo.add(cuerpo, java.awt.BorderLayout.CENTER);

        add(pCentroCabeceraCuerpo, java.awt.BorderLayout.CENTER);

        margenDer.setOpaque(false);

        javax.swing.GroupLayout margenDerLayout = new javax.swing.GroupLayout(margenDer);
        margenDer.setLayout(margenDerLayout);
        margenDerLayout.setHorizontalGroup(
            margenDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        margenDerLayout.setVerticalGroup(
            margenDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        add(margenDer, java.awt.BorderLayout.EAST);

        margenIzq.setOpaque(false);

        javax.swing.GroupLayout margenIzqLayout = new javax.swing.GroupLayout(margenIzq);
        margenIzq.setLayout(margenIzqLayout);
        margenIzqLayout.setHorizontalGroup(
            margenIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        margenIzqLayout.setVerticalGroup(
            margenIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        add(margenIzq, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton bGestBebidas;
    private javax.swing.JPanel cabecera;
    private javax.swing.JPanel centro;
    private javax.swing.JPanel centroDer;
    private javax.swing.JPanel centroIzq;
    private javax.swing.JPanel cuerpo;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel margenDer;
    private javax.swing.JPanel margenDer1;
    private javax.swing.JPanel margenDer2;
    private javax.swing.JPanel margenInf;
    private javax.swing.JPanel margenInf1;
    private javax.swing.JPanel margenInf2;
    private javax.swing.JPanel margenIzq;
    private javax.swing.JPanel margenIzq1;
    private javax.swing.JPanel margenIzq2;
    private javax.swing.JPanel margenSup;
    private javax.swing.JPanel margenSup1;
    private javax.swing.JPanel pCentro;
    private javax.swing.JPanel pCentroCabeceraCuerpo;
    private javax.swing.JPanel pDer;
    private javax.swing.JPanel pDer2;
    private javax.swing.JPanel pIzq;
    private javax.swing.JPanel pIzq2;
    private javax.swing.JPanel panelTextoDer;
    private javax.swing.JPanel panelTextoIzq;
    private javax.swing.JLabel textoDer;
    private javax.swing.JLabel textoIzq;
    // End of variables declaration//GEN-END:variables

}
