/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelListaPedido.java
 *
 * Created on 11-may-2010, 17:42:46
 */

package Vista.InterfazCliente;

import GestionCarta.Elemento;
import GestionCarta.ElementoBebida;
import GestionCarta.ElementoPlato;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos, Modificado por Sergio
 */
public class PanelListaPedido extends javax.swing.JPanel {

    PanelGeneralCliente PGC;
    private int codPedido;

    /** Creates new form PanelListaPedido */
    public PanelListaPedido(ArrayList<Elemento> listaElementos, PanelGeneralCliente PGC, int codPedido, int estado) {
        initComponents();

        this.PGC=PGC;
        this.codPedido=codPedido;

        this.TextoListaComida.setText("PLATOS:");
        Iterator it = listaElementos.iterator();
        int count = 0; // Cuenta los elementos introducidos
        while(it.hasNext()){
            Elemento elemento = (Elemento) it.next();
            if(elemento instanceof ElementoPlato){
                this.TextoListaComida.setText(this.TextoListaComida.getText()+"\n- "+elemento.getNombre());
                count++;
            }
        }
        if(count < listaElementos.size()){ // Si todos los que habian eran platos, hemos terminado
            if(count == 0){ // Si no se introdujo ningun plato, borramos el mensaje "PLATOS"
                this.TextoListaComida.setText("BEBIDAS:");
            }else{
                this.TextoListaComida.setText(this.TextoListaComida.getText()+"\nBEBIDAS:");
            }
            it = listaElementos.iterator();
            while(it.hasNext()){
                Elemento elemento = (Elemento) it.next();
                if(elemento instanceof ElementoBebida){
                    this.TextoListaComida.setText(this.TextoListaComida.getText()+"\n- "+elemento.getNombre());
                }
            }
        }

        if(estado >0 ){
            this.BotonModificar.setVisible(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelListas = new javax.swing.JPanel();
        ScrollListaComida = new javax.swing.JScrollPane();
        TextoListaComida = new javax.swing.JTextPane();
        pBotonModificar = new javax.swing.JPanel();
        pMargenSup = new javax.swing.JPanel();
        BotonModificar = new javax.swing.JButton();
        pMargenIzq = new javax.swing.JPanel();
        pMargenDer = new javax.swing.JPanel();
        pMargenArr = new javax.swing.JPanel();
        pMargenAba = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 172, 229), 3));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        PanelListas.setOpaque(false);
        PanelListas.setLayout(new java.awt.BorderLayout());

        ScrollListaComida.setBorder(null);
        ScrollListaComida.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        TextoListaComida.setBorder(null);
        TextoListaComida.setEditable(false);
        TextoListaComida.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ScrollListaComida.setViewportView(TextoListaComida);

        PanelListas.add(ScrollListaComida, java.awt.BorderLayout.CENTER);

        pBotonModificar.setOpaque(false);
        pBotonModificar.setLayout(new java.awt.BorderLayout());

        pMargenSup.setBackground(new java.awt.Color(255, 255, 255));
        pBotonModificar.add(pMargenSup, java.awt.BorderLayout.NORTH);

        BotonModificar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BotonModificar.setForeground(new java.awt.Color(80, 98, 143));
        BotonModificar.setText("Modificar");
        BotonModificar.setPreferredSize(new java.awt.Dimension(103, 40));
        BotonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarPedido(evt);
            }
        });
        pBotonModificar.add(BotonModificar, java.awt.BorderLayout.CENTER);

        PanelListas.add(pBotonModificar, java.awt.BorderLayout.SOUTH);

        add(PanelListas, java.awt.BorderLayout.CENTER);

        pMargenIzq.setBackground(new java.awt.Color(255, 255, 255));
        add(pMargenIzq, java.awt.BorderLayout.WEST);

        pMargenDer.setBackground(new java.awt.Color(255, 255, 255));
        add(pMargenDer, java.awt.BorderLayout.EAST);

        pMargenArr.setBackground(new java.awt.Color(255, 255, 255));
        add(pMargenArr, java.awt.BorderLayout.NORTH);

        pMargenAba.setBackground(new java.awt.Color(255, 255, 255));
        add(pMargenAba, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void modificarPedido(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarPedido
        Integer estado = this.PGC.obtieneEstadoPedido(codPedido);
        if(estado == 0){
            this.PGC.iniciaModificaPedido(this.codPedido);
            this.PGC.decrementarNumPedidos();
        }else if(estado > 0){
            JOptionPane.showMessageDialog(this,
                              "El pedido ha empezado a prepararse, ",
                              "ya no puede ser modificado",
                              JOptionPane.INFORMATION_MESSAGE);
            this.BotonModificar.setVisible(false);
        }else{
            this.PGC.eliminarPedido(codPedido);
            System.err.println("Hay un error en el estado del pedido "+codPedido+
                    "\nFuncion modificarPedido, en PanelListaPedido.");
        }
    }//GEN-LAST:event_modificarPedido


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonModificar;
    private javax.swing.JPanel PanelListas;
    private javax.swing.JScrollPane ScrollListaComida;
    private javax.swing.JTextPane TextoListaComida;
    private javax.swing.JPanel pBotonModificar;
    private javax.swing.JPanel pMargenAba;
    private javax.swing.JPanel pMargenArr;
    private javax.swing.JPanel pMargenDer;
    private javax.swing.JPanel pMargenIzq;
    private javax.swing.JPanel pMargenSup;
    // End of variables declaration//GEN-END:variables

}
