/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelPedidoRealizado.java
 *
 * Created on 09-may-2010, 17:33:28
 */

package Vista.InterfazCliente;

import GestionCarta.Elemento;
import GestionPedidos.ElementoPedido;
import GestionPedidos.Pedido;
import java.util.ArrayList;
import java.util.Iterator;
import utilidades.PanelEspacioVertical;

/**
 *
 * @author Carlos, Modificado por Sergio
 */
public class PanelPedidoRealizado extends javax.swing.JPanel {

    PanelGeneralCliente panelGeneralCliente;
    private int codMesa;
    /** Creates new form PanelPedidoRealizado */
    public PanelPedidoRealizado(PanelGeneralCliente panelGeneralCliente, int codMesa) {
        initComponents();
        this.panelGeneralCliente=panelGeneralCliente;
        this.codMesa=codMesa;
        this.actualizar();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPanelPedido = new javax.swing.JScrollPane();
        PanelPedido = new javax.swing.JPanel();
        pBotonVerFactura = new javax.swing.JPanel();
        pMargenSup = new javax.swing.JPanel();
        BotonVerFactura = new javax.swing.JButton();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(200, 200));
        setLayout(new java.awt.BorderLayout());

        ScrollPanelPedido.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        PanelPedido.setBackground(new java.awt.Color(255, 255, 255));
        PanelPedido.setOpaque(false);
        PanelPedido.setLayout(new javax.swing.BoxLayout(PanelPedido, javax.swing.BoxLayout.Y_AXIS));
        ScrollPanelPedido.setViewportView(PanelPedido);

        add(ScrollPanelPedido, java.awt.BorderLayout.CENTER);

        pBotonVerFactura.setOpaque(false);
        pBotonVerFactura.setLayout(new java.awt.BorderLayout());

        pMargenSup.setOpaque(false);
        pMargenSup.setLayout(new java.awt.BorderLayout());
        pBotonVerFactura.add(pMargenSup, java.awt.BorderLayout.NORTH);

        BotonVerFactura.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        BotonVerFactura.setForeground(new java.awt.Color(80, 98, 143));
        BotonVerFactura.setText("Ver Factura");
        BotonVerFactura.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(150, 172, 229), 1, true));
        BotonVerFactura.setPreferredSize(new java.awt.Dimension(89, 50));
        BotonVerFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verFactura(evt);
            }
        });
        pBotonVerFactura.add(BotonVerFactura, java.awt.BorderLayout.SOUTH);

        add(pBotonVerFactura, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void verFactura(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verFactura
        this.panelGeneralCliente.verFactura();
    }//GEN-LAST:event_verFactura


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonVerFactura;
    private javax.swing.JPanel PanelPedido;
    private javax.swing.JScrollPane ScrollPanelPedido;
    private javax.swing.JPanel pBotonVerFactura;
    private javax.swing.JPanel pMargenSup;
    // End of variables declaration//GEN-END:variables

    public void anadirPedido(ArrayList<Elemento> listaElementos, int codPedido, int estado) {
        this.PanelPedido.add(new PanelListaPedido(listaElementos, panelGeneralCliente, codPedido, estado));
        this.PanelPedido.add(new PanelEspacioVertical());
    }

    public int actualizar() {
        this.PanelPedido.removeAll();
        ArrayList<Pedido> pedidos = this.panelGeneralCliente.icliente.obtienePedidosMesa(codMesa);
        Iterator itPedidos = pedidos.iterator();
        while(itPedidos.hasNext()){
            Pedido pedido = (Pedido) itPedidos.next();
            ArrayList<ElementoPedido> listaElementosPedido = pedido.obtieneElementos();

            ArrayList<Elemento> listaElementos = new ArrayList();
            Iterator itElementos = listaElementosPedido.iterator();
            while(itElementos.hasNext()){
                ElementoPedido elementoPedido = (ElementoPedido) itElementos.next();
                listaElementos.add(elementoPedido.getElemento());
            }

            if(pedido.getEstado()<2){
                this.anadirPedido(listaElementos,pedido.getCodPedido(), pedido.getEstado());
            }
            //this.panelGeneralCliente.eliminarPedido(pedido.getCodPedido(), false);
        }

        if(pedidos.size()==0){
            this.BotonVerFactura.setEnabled(false);
        }else{
            this.BotonVerFactura.setEnabled(true);
        }

        this.PanelPedido.revalidate();
        this.PanelPedido.repaint();

        return pedidos.size();
    }

}
