/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelPedidoRealizado.java
 *
 * Created on 09-may-2010, 17:33:28
 */

package Vista.InterfazCliente;

import GestionCarta.Elemento;
import GestionPedidos.ElementoColaBar;
import GestionPedidos.ElementoColaCocina;
import GestionPedidos.ElementoPedido;
import GestionPedidos.Pedido;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Vector;
import utilidades.PanelEspacioVertical;

/**
 *
 * @author Carlos, Modificado por Sergio
 */
public class PanelPedidoRealizado extends javax.swing.JPanel {

    PanelGeneralCliente panelGeneralCliente;
    private Vector<Vector<Integer> > pedidosMostrandose;
    private int codMesa;
    /** Creates new form PanelPedidoRealizado */
    public PanelPedidoRealizado(PanelGeneralCliente panelGeneralCliente, int codMesa) {
        initComponents();
        this.panelGeneralCliente=panelGeneralCliente;
        this.codMesa=codMesa;
        this.pedidosMostrandose = new Vector<Vector<Integer> >();
        this.actualizar();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPanelPedido = new javax.swing.JScrollPane();
        PanelPedido = new javax.swing.JPanel();
        pMargenBoton = new javax.swing.JPanel();
        pMargenSuperiorBoton = new javax.swing.JPanel();
        BotonVerFactura = new javax.swing.JButton();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(200, 200));
        setLayout(new java.awt.BorderLayout());

        ScrollPanelPedido.setBorder(null);
        ScrollPanelPedido.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ScrollPanelPedido.setOpaque(false);

        PanelPedido.setBackground(new java.awt.Color(255, 255, 255));
        PanelPedido.setOpaque(false);
        PanelPedido.setLayout(new javax.swing.BoxLayout(PanelPedido, javax.swing.BoxLayout.Y_AXIS));
        ScrollPanelPedido.setViewportView(PanelPedido);

        add(ScrollPanelPedido, java.awt.BorderLayout.CENTER);

        pMargenBoton.setOpaque(false);
        pMargenBoton.setLayout(new java.awt.BorderLayout());

        pMargenSuperiorBoton.setOpaque(false);
        pMargenBoton.add(pMargenSuperiorBoton, java.awt.BorderLayout.NORTH);

        BotonVerFactura.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        BotonVerFactura.setForeground(new java.awt.Color(80, 98, 143));
        BotonVerFactura.setText("Ver Factura");
        BotonVerFactura.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(150, 172, 229), 1, true));
        BotonVerFactura.setPreferredSize(new java.awt.Dimension(89, 50));
        BotonVerFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verFactura(evt);
            }
        });
        pMargenBoton.add(BotonVerFactura, java.awt.BorderLayout.CENTER);

        add(pMargenBoton, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void verFactura(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verFactura
        this.panelGeneralCliente.verFactura();
    }//GEN-LAST:event_verFactura


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonVerFactura;
    private javax.swing.JPanel PanelPedido;
    private javax.swing.JScrollPane ScrollPanelPedido;
    private javax.swing.JPanel pMargenBoton;
    private javax.swing.JPanel pMargenSuperiorBoton;
    // End of variables declaration//GEN-END:variables

    public void anadirPedido(ArrayList<Elemento> listaElementos, int codPedido, int estado) {
        this.PanelPedido.add(new PanelListaPedido(listaElementos, panelGeneralCliente, codPedido, estado));
        this.PanelPedido.add(new PanelEspacioVertical());
    }

    public int actualizar() {
        // Comprobamos si ha cambiado algun pedido
        ArrayList<Pedido> pedidos = this.panelGeneralCliente.icliente.obtienePedidosMesa(codMesa);
        if(pedidos == null){
            if(pedidosMostrandose != null)
                this.pedidosMostrandose.clear();
            this.PanelPedido.removeAll();
            this.panelGeneralCliente.volverAlInicio();
        }else if(hayQueActualizar(pedidosMostrandose, pedidos)) {
            if(pedidosMostrandose != null)
                this.pedidosMostrandose.clear();
            this.pedidosMostrandose = this.copiarPedido(pedidos);

            // Si ha cambiado, repintamos
            this.PanelPedido.removeAll();

            Iterator itPedidos = pedidos.iterator();
            boolean todosPagados = true;
            while (itPedidos.hasNext()) {
                Pedido pedido = (Pedido) itPedidos.next();
                ArrayList<ElementoPedido> listaElementosPedido = pedido.obtieneElementos();

                ArrayList<Elemento> listaElementos = new ArrayList();
                Iterator itElementos = listaElementosPedido.iterator();
                while (itElementos.hasNext()) {
                    ElementoPedido elementoPedido = (ElementoPedido) itElementos.next();
                    listaElementos.add(elementoPedido.getElemento());
                }

                if (pedido.getEstado() != Pedido.FACTURADO) {
                    ArrayList<ElementoPedido> elementos = pedido.getElementos();
                    Iterator<ElementoPedido> it = elementos.iterator();
                    boolean mostrar = false;
                    // Iteramos sobre todos los elementos, si todos han sido preparados...
                    // ...no lo mostramos en la interfaz
                    while (it.hasNext() && !mostrar) {
                        ElementoPedido ep = it.next();
                        if (ep instanceof ElementoColaBar) {
                            if (ep.getEstado() != ElementoColaBar.PREPARADO) {
                                mostrar = true;
                            }
                        } else if (ep instanceof ElementoColaCocina) {
                            if (ep.getEstado() != ElementoColaCocina.PREPARADO) {
                                mostrar = true;
                            }
                        }
                    }
                    if (mostrar) {
                        this.anadirPedido(listaElementos, pedido.getCodPedido(), pedido.getEstado());
                    }
                    todosPagados = false;
                }
                //this.panelGeneralCliente.eliminarPedido(pedido.getCodPedido(), false);
            }

            if (todosPagados == true) {
                this.panelGeneralCliente.volverAlInicio();
            } else {
                if (pedidos.size() == 0) {
                    this.BotonVerFactura.setEnabled(false);
                } else {
                    this.BotonVerFactura.setEnabled(true);
                }

                this.PanelPedido.repaint();
                this.PanelPedido.revalidate();
            }
        } else{
            System.gc();
        }
        
        return pedidos.size();
    }

    /**
     * Comprueba si es necesario actualizar
     * @param pedMostrandose Vector de &gt;CodPedido, EstadoPedido, CodElem, EstadoElem...&lt;
     * @param ped
     * @return
     */
    private boolean hayQueActualizar(Vector<Vector<Integer> > pedsMostrandose, ArrayList<Pedido> peds) {
        if((pedsMostrandose == null && peds != null) ||
                    (pedsMostrandose != null && peds == null))
                return true;
        if(pedsMostrandose == null && peds == null) return false;
        if((peds.isEmpty() && !pedsMostrandose.isEmpty()) ||
                (!peds.isEmpty() && pedsMostrandose.isEmpty())){
            return true;
        }
        if(peds.isEmpty() && pedsMostrandose.isEmpty()) return false;

        if(pedsMostrandose.size() != peds.size()) return true;
        Iterator<Vector<Integer> > itMostrandose = pedsMostrandose.iterator();
        while(itMostrandose.hasNext()){
            Vector<Integer> pedMostrandose = itMostrandose.next();
            Iterator<Pedido> itPeds = peds.iterator();
            Pedido ped = null;
            // Buscamos el pedido dentro de nuestra lista de pedidos mostrandose
            boolean encontrado = false;
            while(itPeds.hasNext() && !encontrado){
                ped = itPeds.next();
                if(ped.getCodPedido() == pedMostrandose.get(0)){
                    encontrado = true;
                }
            }
            if(!encontrado) return true;
            if(pedMostrandose.get(1) != ped.getEstado()) return true;
            ArrayList<ElementoPedido> elementos = ped.getElementos();
            // No se puede comparar los tamaños porque pedMostrandose solo guarda los que corresponde al filtro
            //if((pedMostrandose.size()-2)/2 != elementos.size()) return true;

            // Buscamos la correspondencia entre elementos
            Iterator<ElementoPedido> iterator = elementos.iterator();
            while(iterator.hasNext()){
                ElementoPedido elem = iterator.next();
                if(elem instanceof ElementoColaCocina){
                    encontrado = false;
                    for(int i=2; i< pedMostrandose.size() && !encontrado; i+=2){
                        if(pedMostrandose.get(i) == elem.getCodElementoPedido()){
                            encontrado = true;
                            if(pedMostrandose.get(i+1) != elem.getEstado()){
                                return true;
                            }
                        }
                    }
                }
            }
        }

        return false;
    }
    
    /**
     * Copia una lista de pedidos y lo devuelve en forma de vector de codigos y estados.
     * @param peds Pedidos a copiar
     * @return Nuevo pedido sin referencias a peds
     */
    private Vector<Vector<Integer> > copiarPedido(ArrayList<Pedido> peds){

        Vector<Vector<Integer> > copiaPeds = new Vector(peds.size());
        Iterator<Pedido> itPeds = peds.iterator();

        while(itPeds.hasNext()){
            Pedido ped = itPeds.next();
            Vector<Integer> copia = new Vector<Integer>(ped.getElementos().size()*2 +2);
            copia.add(ped.getCodPedido());
            copia.add(ped.getEstado());

            Iterator<ElementoPedido> it = ped.getElementos().iterator();
            while(it.hasNext()){
                ElementoPedido next = it.next();
                if(next instanceof ElementoColaCocina){
                    copia.add(next.getCodElementoPedido());
                    copia.add(next.getEstado());
                }
            }
            copiaPeds.add(copia);
        }
        return copiaPeds;
    }

}
