/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelListaPedido.java
 *
 * Created on 11-may-2010, 17:42:46
 */

package Vista.InterfazCliente;

import GestionCarta.Elemento;
import GestionCarta.ElementoPlato;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class PanelListaPedido extends javax.swing.JPanel {

    PanelGeneralCliente PGC;
    private int codPedido;

    /** Creates new form PanelListaPedido */
    public PanelListaPedido(ArrayList<Elemento> listaElementos, PanelGeneralCliente PGC, int codPedido, int estado) {
        initComponents();

        this.PGC=PGC;
        this.codPedido=codPedido;

        this.TextoListaComida.setText("PLATOS:\n");
        this.TextoListaBebida.setText("BEBIDAS:\n");
        
        Iterator it = listaElementos.iterator();

        while(it.hasNext()){
            Elemento elemento = (Elemento) it.next();

            if(elemento instanceof ElementoPlato){
                this.TextoListaComida.setText(this.TextoListaComida.getText()+"\n- "+elemento.getNombre());
            }else{
                this.TextoListaBebida.setText(this.TextoListaBebida.getText()+"\n- "+elemento.getNombre());
            }
        }

        if(estado!=0){
            this.BotonModificar.setVisible(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelListas = new javax.swing.JPanel();
        ScrollPedido = new javax.swing.JScrollPane();
        PanelPedidoRealizado = new javax.swing.JPanel();
        ScrollListaComida = new javax.swing.JScrollPane();
        TextoListaComida = new javax.swing.JTextPane();
        ScrollBebida = new javax.swing.JScrollPane();
        TextoListaBebida = new javax.swing.JEditorPane();
        pBotonModificar = new javax.swing.JPanel();
        pMargenSup = new javax.swing.JPanel();
        BotonModificar = new javax.swing.JButton();
        pMargenIzq = new javax.swing.JPanel();
        pMargenDer = new javax.swing.JPanel();
        pMargenArr = new javax.swing.JPanel();
        pMargenAba = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 172, 229), 3));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        PanelListas.setLayout(new java.awt.BorderLayout());

        PanelPedidoRealizado.setLayout(new javax.swing.BoxLayout(PanelPedidoRealizado, javax.swing.BoxLayout.Y_AXIS));

        ScrollListaComida.setBorder(null);
        ScrollListaComida.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        TextoListaComida.setBorder(null);
        TextoListaComida.setEditable(false);
        ScrollListaComida.setViewportView(TextoListaComida);

        PanelPedidoRealizado.add(ScrollListaComida);

        ScrollBebida.setBorder(null);

        TextoListaBebida.setBorder(null);
        ScrollBebida.setViewportView(TextoListaBebida);

        PanelPedidoRealizado.add(ScrollBebida);

        ScrollPedido.setViewportView(PanelPedidoRealizado);

        PanelListas.add(ScrollPedido, java.awt.BorderLayout.CENTER);

        pBotonModificar.setOpaque(false);
        pBotonModificar.setLayout(new java.awt.BorderLayout());

        pMargenSup.setOpaque(false);
        pBotonModificar.add(pMargenSup, java.awt.BorderLayout.NORTH);

        BotonModificar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        BotonModificar.setForeground(new java.awt.Color(80, 98, 143));
        BotonModificar.setText("Modificar");
        BotonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarPedido(evt);
            }
        });
        pBotonModificar.add(BotonModificar, java.awt.BorderLayout.CENTER);

        PanelListas.add(pBotonModificar, java.awt.BorderLayout.SOUTH);

        add(PanelListas, java.awt.BorderLayout.CENTER);

        pMargenIzq.setOpaque(false);
        add(pMargenIzq, java.awt.BorderLayout.WEST);

        pMargenDer.setOpaque(false);
        add(pMargenDer, java.awt.BorderLayout.EAST);

        pMargenArr.setOpaque(false);
        add(pMargenArr, java.awt.BorderLayout.NORTH);

        pMargenAba.setOpaque(false);
        add(pMargenAba, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void modificarPedido(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarPedido
        if(this.BotonModificar.isEnabled()){
            this.PGC.iniciaModificaPedido(this.codPedido);
        }else{
            JOptionPane.showMessageDialog(this,
                              "El pedido ha empezado a prepararse, ",
                              "ya no puede ser modificado",
                              JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_modificarPedido


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonModificar;
    private javax.swing.JPanel PanelListas;
    private javax.swing.JPanel PanelPedidoRealizado;
    private javax.swing.JScrollPane ScrollBebida;
    private javax.swing.JScrollPane ScrollListaComida;
    private javax.swing.JScrollPane ScrollPedido;
    private javax.swing.JEditorPane TextoListaBebida;
    private javax.swing.JTextPane TextoListaComida;
    private javax.swing.JPanel pBotonModificar;
    private javax.swing.JPanel pMargenAba;
    private javax.swing.JPanel pMargenArr;
    private javax.swing.JPanel pMargenDer;
    private javax.swing.JPanel pMargenIzq;
    private javax.swing.JPanel pMargenSup;
    // End of variables declaration//GEN-END:variables

}
